apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netdata
  namespace: default
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: netdata
      version: '>=3.7.0'
      sourceRef:
        kind: HelmRepository
        name: netdata-repo
        namespace: flux-system
  releaseName: netdata
  targetNamespace: monitoring
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    image:
      tag: "stable"
    parent:
      enabled: false
    child:
      persistence:
        enabled: "false"
    k8sState:
      enabled: false
  valuesFrom:
  - kind: Secret
    name: netdata-secret
    valuesKey: netdata