apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: homepage-official
  namespace: flux-system
spec:
  image: ghcr.io/nohoster/homepage
  interval: 10m0s

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: homepage-image
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homepage-official
  policy:
    semver:
      range: '>0.0.0'

