apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: voyager-official
  namespace: flux-system
spec:
  image: ghcr.io/aeharding/voyager
  interval: 10m0s

---

apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: voyager-image
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: voyager-official
  policy:
    semver:
      range: '<2.0.0' 
#avoid updating to 2.0
      

