apiVersion: apps/v1
kind: Deployment
metadata:
  name: redlib
  namespace: default
  labels:
    app: redlib
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redlib
  template:
    metadata:
      labels:
        app: redlib
    spec:
      automountServiceAccountToken: false
      containers:
      - name: redlib
        # image: ghcr.io/nohoster/redlib:latest
        image: quay.io/redlib/redlib:latest
        livenessProbe:
          httpGet:
            path: "/settings"
            port: 8080
        ports:
        - containerPort: 8080
        env:
        - name: REDLIB_DEFAULT_THEME
          value: "black"
        - name: REDLIB_ROBOTS_DISABLE_INDEXING
          value: "on"
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 10010
          runAsNonRoot: true
          runAsUser: 10010
          allowPrivilegeEscalation: false
          capabilities: 
            drop: 
            - ALL
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
      imagePullSecrets:
      - name: ghcr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: redlib-svc
  namespace: default
spec:
  selector:
    app: redlib
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
