apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nohost-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/production/
  prune: true
  sourceRef:
    kind: GitRepository
    name: nohost-network
