apiVersion: v1
kind: Namespace
metadata:
  name: external-dns

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api
  namespace: external-dns
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secrets
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-secret
  data:
  - secretKey: api-token
    remoteRef:
      key: cloudflare
      property: api-token
  - secretKey: api-email
    remoteRef:
      key: cloudflare
      property: api-email

---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns-repo
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: external-dns
      version: '>=6.44.0'
      sourceRef:
        kind: HelmRepository
        name: external-dns-repo
        namespace: flux-system
  releaseName: external-dns
  targetNamespace: external-dns
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    provider: "cloudflare"
    sources: ["ingress"]
    cloudflare.proxied: false
  valuesFrom:
  - kind: Secret
    name: cloudflare-api-secret
    targetPath: cloudflare.apiToken
    valuesKey: api-token 
  - kind: Secret
    name: cloudflare-api-secret
    targetPath: cloudflare.email
    valuesKey: api-email

