apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets-repo
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.external-secrets.io

---

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets-repo
        namespace: flux-system
      version: ">=0.9.0"
  interval: 1h0m0s
  releaseName: external-secrets
  targetNamespace: external-secrets
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
