---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluent-repo
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://fluent.github.io/helm-charts

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: monitoring
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: fluent-bit
      version: '>=0.37.0'
      sourceRef:
        kind: HelmRepository
        name: fluent-repo
        namespace: flux-system
  releaseName: fluentbit
  targetNamespace: monitoring
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: fluentbit-values
  - kind: Secret
    name: fluent-output-secret
    targetPath: config.outputs
