---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis-repo
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://registry-1.docker.io/bitnamicharts/redis
  type: "oci"
