---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis-repo
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: oci://registry-1.docker.io/bitnamicharts
  type: "oci"

---

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nitter-redis
  namespace: default
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: redis-repo
        namespace: flux-system
      version: ">=17.15.0"
  interval: 1h0m0s
  releaseName: nitter-redis
  targetNamespace: default
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    architecture: "standalone"
    auth:
      enabled: false
    master:
      kind: "Deployment"
      persistence:
        enabled: false
