apiVersion: apps/v1
kind: Deployment
metadata:
  name: librey
  namespace: default
  labels:
    app: librey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librey
  template:
    metadata:
      labels:
        app: librey
    spec:
      automountServiceAccountToken: false
      containers:
      - name: librey
        image: ghcr.io/ahwxorg/librey:latest
        ports:
        - containerPort: 8080
        #securityContext:
        #  readOnlyRootFilesystem: true
        #  runAsGroup: 1000
        #  runAsNonRoot: true
        #  runAsUser: 1000
        #  allowPrivilegeEscalation: false
        #  capabilities: 
        #    drop: 
        #    - ALL
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "400Mi"
        env:
        - name: PUID
          value: "1000"
        - name: GUID
          value: "1000"
        - name: VERSION
          value: docker
        - name: TZ
          value: "America/Mexico_City"
        - name: CONFIG_GOOGLE_DOMAIN
          value: "com"
        - name: CONFIG_TEXT_SEARCH_ENGINE
          value: "auto"
        - name: CONFIG_GOOGLE_LANGUAGE
          value: "en"
        - name: CONFIG_WIKIPEDIA_LANGUAGE
          value: "en"
        - name: APP_LIBREREDDIT
          value: "https://libreddit.nohost.network"
        - name: APP_NITTER
          value: "https://nitter.nohost.network"
        - name: APP_RIMGO
          value: "https://rimgo.nohost.network"
        - name: APP_BREEZEWIKI
          value: "https://breeze.nohost.network"
        - name: CONFIG_INSTANCE_FALLBACK
          value: "true"

---

apiVersion: v1
kind: Service
metadata:
  name: librey-svc
  namespace: default
spec:
  selector:
    app: librey
  type: ClusterIP

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
