apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: invidious-config-secret
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secrets
    kind: ClusterSecretStore
  target:
    name: invidious-config-secret
  data:
  - secretKey: INVIDIOUS_CONFIG 
    remoteRef:
      key: invidious
      property: INVIDIOUS_CONFIG 
