apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nohost-issuer
  namespace: default
spec:
  acme:
    email: admin@nohost.network
    privateKeySecretRef:
      name: nohost-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token-secret