apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secrets
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
  data:
  - secretKey: api-token
    remoteRef:
      key: cloudflare
      property: api-token