apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: codeberg-secret
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secrets
    kind: SecretStore
  target:
    name: codeberg-secret
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: codeberg
      property: .dockerconfigjson