apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluent-output-secret
  namespace: monitoring
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secrets
    kind: ClusterSecretStore
  target:
    name: fluent-output-secret
  data:
  - secretKey: values.yaml
    remoteRef:
      key: fluentbit
      property: values.yaml
