apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-remote-secret
  namespace: monitoring
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secrets
    kind: ClusterSecretStore
  target:
    name: prometheus-remote-secret
  data:
  - secretKey: username
    remoteRef:
      key: prometheus
      property: username
  - secretKey: password
    remoteRef:
      key: prometheus
      property: password
  - secretKey: username-selfhosted
    remoteRef:
      key: prometheus
      property: username-selfhosted
  - secretKey: password-selfhosted
    remoteRef:
      key: prometheus
      property: password-selfhosted

