apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nohost-repo-secret
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secrets
    kind: ClusterSecretStore
  target:
    name: nohost-repo-secret
    engineVersion: v1
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: nohost-repo
      property: .dockerconfigjson
