apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repocr-secret
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secrets
    kind: ClusterSecretStore
  target:
    name: repocr-secret
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: repocr
      property: .dockerconfigjson
