apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secrets
  namespace: default
spec:
  provider:
    vault:
      server: "https://vault.nohost.network"
      path: "nohost-secrets"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token-secret"
          namespace: "default"
          key: "token"
