apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secrets
  namespace: default
spec:
  provider:
    vault:
      server: "https://almacen.nohost.network:8200"
      path: "nohost-secrets"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token-secret"
          key: "token"
