apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgCu7+cdUI9bxgLzvBxiCdpXIRsF7r8HesDA9zTE8zuqTKRjIIF89jLi2QY6smI8vMxC8YdBtf1ua6HVaXL0I3ZRXjXTUGcgIvsaosuc/M89Vp/Gu4Qy5X8uVvnzLeZCE9RCLyjtji9avBKTS/NMValSfdMw5m7kh6htLzlOhnVCu9+JEA6SdPX9LOCnpgDaXZIUkAc/CXh2Sj8fo2M4ofbnoSVChnfw3818GkVTF7JbhA8BPJ0+Qk1E3xwhtIduWfcUSNwtkWiOqBp/1y6iwJUVK4mF6uJlRM8mOI0UymeUCur1UinhpkAwcd/Padn+CifPTXOqD4YYi6XLtzFtfl/hGmxXKl70/HdrsFCTn0V5KQ7TsELGYSpwvmhj6gRvUqIjBsq+dpznyIpYpjLmsIZfNqoT6gjbjE/epXU9y+oaX9xrisqNG7dftAKPrT//YpUBhwfuj04KvTlfinsyMO81nuTGI5oYDdyorqvgibyzHio/Ye4+ByYoUVXPrWausyWFGY6cx77ETLgwGUbDEUbPKE3qyEebWEY0hvktrtFTcV/0k99Yw0AKIP0MVelMOzc8kJHo7cP5CjJJWvvb6AMxXtnyXDmu2pt32vu/VJc3KTYlMtIjwjQR8r89Kg7u4U3avqSNoNjkaoFqIOq5aaDNgBRb3o6k5Fari22iwXn/izx1nKaizYpNJXqAB6W7Pzb6CoEQliieA/2lh6N9p/4sQTR6TW0bBsiHXSDALVPStk/c3cy084Wy
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default
    type: Opaque

