apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: codeberg-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBmpCJjSDAigb02NGTOT16EwS8v2t3IGvxZpTaWwAJUB+EwlgV/Fm0MlJJQDRsVimwJNgLyg6wPK9XEfpyuYSqQF6yfusnC3YfvYU+4Ri6C7aSbOGxe0DwKuEvYKkXWPEz3ke+ZgjSbEf0eMgoyH+kZOmmFjKsBFocNLO2vk/DNZMVIMzzD989M4IZ5x7k0QZdj5HEMrqjIt2JZeayZCdxYzQUtN/l95KTGKAYukaLu+76rpRIKFflC8sJMNIZhnhrvnoT9yzNAjVqQePbFuJhPm7nfqb26Np50xUP9+vHXxlQKngztXIHf63QQUSetDhLVUyMPnz5ix4wur3ji32r3rkQoCo+4UJ9BHIOJi4ZMrdDx3xsZs12eQNxs9Rx48+KwNJYVbW8S3xxN0Ym+TGegM9+KkP0ozMgdIgwXPlEIRPs7hQ8wAWROJiLqjJJqwxtuw0bfgUv/4km1MoDeK3t2SAk4oYkm1a+2nPnVWhRGHU1ibzVHGm9U9bNF69X0swjN84nLeW+YmRabb+912iQzurUseH+M9mq33Hbq/LgD64108fsjJXu4Tw9w5rOjSOR2nedU5a51XI07JUMj7/j+1gR758dJKe0TUIozQC6FwGlm7Yxd3HMOyBJMsgtCK5s3ffGQJm0tSymrB1F3zysnRP/Fu9jaOhcclNNnV0PL+uL7CtBofw0aRWoVU/Do0KWuHK9EOItMb74lsIiePwQvyCRt4zZDci85VGZbdyAb0JyEvPUXiJp/7EEOGl9GyVpGkY/gOaJNN88UUjd34+b0INDV9XDgrimzXI5Lp1zAyT8kg2QW3e5Kq0JTYjxqbNeRWNKMpT3+euodVioiQj8DmVtoE2PR3mqLPJrPa8sci+ofiHhsv2gxmZ2nd999z11Z+6JVmxYiu85ck7+jgKuDSN62AJIVIZhVN9kOT7RxG6/lvkSbcWepFBTMuJoGtQ==
  template:
    metadata:
      creationTimestamp: null
      name: codeberg-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson

