apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: codeberg-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAhQ5sd2Tp4BWYrXWb+cfVA+GnTbVkv8BhOassJ6PaNRCHoud54QAwbWZLaBirs/OvRQCfYBTGfy8YfslFqUOTPM5y7xq7ls4A4BH21rQApXGqRZvoIEKIqbmgT+ccMfmBbd6ACrOipXg7PryzhuevgPLAsL85jhpnRptNSaU1Gtwf4vdk/T5eENww1q6QLyEkHRjtJHTIUwGWdkPwunmdGMjTikU/IC1q/vqhnqPT1AIGpxFYzoOUq7+N/1vJxNd/nnAuaKLTC4F0z+qQKkzIKgOZ9SEU97mfdeIXffPIxen92V+SIvnvjPNKuQ5y5Cb1/kQtohZSzK9Q8GYJ5AUF2a1bUdQazWA5zfDBxmPlE0kr+ekCg6PEUYD4LH0PSNE+A+dVP238LAAVGFkB1vZaN9AvPoMvDSWhId4sxecfZW/fB61/2uqd4ms1rzKbfcRrk7H5TIRKcuOqmQPcnSSMu6C3XlRF2J2Gdf4V3BU3QW8HSUKObsVCk+hk64c7uQeMvXXuJDapUfi7CB55EB1iqvK6jwlLMxmlCjKYaJ//NX3FZ7Mv+jrYcC1+dFa7QZpHPgMVDXKJXtlF/fENiXO6XNoQhXWE7ECou8GmHPNAMfz3Fm7+AjO6IDo8Rm8Irb8DqKnSADNJxvFrWS1SlbHqFl+F0HD7IloXD4sRcdxHRMjUzNf8Wt8l9tSz+2l4VZ65D1XatUdlLymvSfLpKdD/wnTDlDtFo4sAb2jEm0bki+cdR5zNyEoEt36xmh096ir1jfhfvgktKhwNjZnST7su1TY4sOOnhHCINmGGrr9/hjNUlafRpQ7Jsd/tdAa4Nkpeb9T4uTOG27Lx39Qip/sL2sQawJLg2Nap/lNTS4CrRNlFMFDzoVNLASbhQdbYedueKDo0SxKFVA9pDHUlvn6jzKAkebQ+o4+lM+8bjZWJPYgiUsLrEvtWcyLznyD6QQw==
  template:
    metadata:
      creationTimestamp: null
      name: codeberg-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson

