apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netdata-secret
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secrets
    kind: SecretStore
  target:
    name: netdata-secret
  data:
  - secretKey: netdata
    remoteRef:
      key: netdata