apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nitter-conf-external
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-secrets
    kind: SecretStore
  target:
    name: nitter-secrets
  data:
  - secretKey: nitter.conf
    remoteRef:
      key: nitter
      property: nitter.conf
  - secretKey: guest_accounts.json
    remoteRef:
      key: nitter
      property: guest_accounts.json
