apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-remote-secret
  namespace: monitoring
spec:
  encryptedData:
    password: AgBgj8kyG6UD5I30Wi7ABd/FvV3EudJZ0DxL1KvEebvzPBrkHuVkVQcQ2/4wJ1Z3LNtaK3rXY19IWGu9DOfyRZKDjuTZUWTkZsrn+6chXctlLIFG1W+y23lh3COVz0tZR/xGsfHKyxwQo00dcB8VNa14KuFiS87waEZzNlcB7g7Tv8PdLZ3snegqA1SdjG7MmxCwGYHh66W/ZFPKUjtDcFgFqpawr7g1Q47DLpHI6OoTkxZG46g3ZUy2gpEdsPxs/845AnE60BHkB/mIJY646UNWeSsDUc7npH6ZtV8jQ+s3H5B21Qsy/n25hqx6h2p7UGXOzbmNrqvA8oGf2RAiHAYb+oS04Vm6npQABJQqfKC0eiN292n/6eLpKWW17Ca0pNKCfFXT10d/wITFT4apzbMHWsjvB+gf2FAFi/WiarI0iBHPruXuIrAbIckoXsn1wo6jF/K285slbVmgdYmYDR1/82sC9lNZ+sbgx/KUEXbEB6XA1v2eK7aczktywJWrzNRxTPdjSlQy5zs7mhoNBqb00Ac6FkqP3zF4U78C/YsZ2YhnP6DZ0jbNSypht2aOhR/5jWZAINFM5uzxBlmpVH2FOzNs9aqSexmViYUyFHdH2gKceimm58dvnxCoIHJTVCRZKm1xVK4cBwxpmsPhxYwFI6oSHZlCZqQkuwxPC0mR43VlZMW5H472AQ2KPcjAddPyYb5QsbH98kt7apBAeuofDJP+qfeT1+zJbXYW4YoumanSK/MnX1KQebCCD54/zHz3r/XNyoxpdfpULkSWYZXToFTYzR+wEIOTc0SSX3ad296BLNELQcEoWtr31CHh6vu3GDxH
    username: AgC5wBJIEcTYV1/ZfBWW6RpUEnrLejL+FHCj4r8IPD9qzZ9WYrhqE4s3RRPS5fEJaJLegeEOsS8gcksmVNMOwGR9ShKiN+bczsxnTTR72gd9i/8hiEm/2YUkw7S0hKJ5hlw6xpEDw+KEWozj9uTUPrp7W60EhvkAT1lPew2kMq3vTgddiqMm9z+y3UZ805vKHIqybmgXbCm+SgsIZp18TLXUCzHBYCgOD8d3QAlU87onfIjRB10Wlcie69a4KeGHZb4IQ6Pk4HjJ1Rf6BOwJZr9yrpvrLrlRykBL3zd3dRzBIPZ62XtMjx4BW1oGISJKLw+iIhLBvoQkZMOAgJONyMzVIiA+Wxtn4S0oEt0JbEuN2H7aLrtbzNod3b5ZfnhXgLXCI3SrYjBhsCfrdcMlZY/LXxy+GfnX2YeY0tCAdH90Nw9P8T8I0dUQ4VoCnkoWEKfIwvYV1LEuIP69HldPtgwbJqwZVDEr8YJzA7uSryliQXpVLKvTeBsU02mf7qvxod5pxy/1UvP35sQx+8Im1sPJxC87d8Z5CDNb0Y8RJ/ih5ndVvxhNCUTTR9MpMJoeqO2sTyIU7DmyfnEjfyIhA6WHUZIWE1LNEtBECFVC4LvEr/w4M7qLaPFzxZx5yJibmPRxCZsxxDpLV3U3jyM8K/gFzEJg4LbdOfLZJd5Lzu+ZBDlMaaKyoN14L+WvGumnFyNDAXWmFIvI
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-remote-secret
      namespace: monitoring
    type: Opaque

